image: docker:stable
services:
    - docker:dind
variables:
    DOCKER_DRIVER: overlay2
    GCP_ECR: '${GCP_GAR}'
    PROJECT_NAME: thousandfund
stages:
    - generate

uat-generate:
    only:
        - develop
    image: node:16
    tags:
        - runner1
    stage: generate
    script:
        - npm i
        - echo "\nVITE_SHA = $CI_COMMIT_SHORT_SHA" >> ./.env.uat
        - npm run generate:uat
        - echo name:$PROJECT_NAME >> ./dist/releasenote.txt
        - export PROJECT_VERSION=$(node -p "require('./package.json').version")
        - echo version:$PROJECT_VERSION >> ./dist/releasenote.txt
        - echo env:uat >> ./dist/releasenote.txt
        - echo sha:$CI_COMMIT_SHORT_SHA >> ./dist/releasenote.txt
        - echo trigger:$CI_COMMIT_REF_NAME >> ./dist/releasenote.txt
        - tar zcvf dist-uat.tar.gz ./dist
    artifacts:
        name: '$PROJECT_NAME $CI_COMMIT_SHORT_SHA uat'
        paths:
            - dist-uat.tar.gz
        expire_in: 1 week

generate:
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG !~ /^*-dev$/

    image: node:16
    tags:
        - runner1
    stage: generate
    script:
        - npm i
        - npm run generate
        - echo name:$PROJECT_NAME >> ./dist/releasenote.txt
        - export PROJECT_VERSION=$(node -p "require('./package.json').version")
        - echo version:$PROJECT_VERSION >> ./dist/releasenote.txt
        - echo env:prod >> ./dist/releasenote.txt
        - echo sha:$CI_COMMIT_SHORT_SHA >> ./dist/releasenote.txt
        - echo trigger:$CI_COMMIT_REF_NAME >> ./dist/releasenote.txt
        - tar -zcvf dist.tar.gz ./dist
    artifacts:
        name: '$PROJECT_NAME $CI_COMMIT_REF_NAME prod'
        paths:
            - dist.tar.gz
        expire_in: 1 week

uat-tag-generate:
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^*-dev$/

    image: node:16
    tags:
        - runner1
    stage: generate
    script:
        - npm i
        - npm run generate:uat
        - echo name:$PROJECT_NAME >> ./dist/releasenote.txt
        - export PROJECT_VERSION=$(node -p "require('./package.json').version")
        - echo version:$PROJECT_VERSION >> ./dist/releasenote.txt
        - echo env:uat >> ./dist/releasenote.txt
        - echo sha:$CI_COMMIT_SHORT_SHA >> ./dist/releasenote.txt
        - echo trigger:$CI_COMMIT_REF_NAME >> ./dist/releasenote.txt
        - tar zcvf dist-uat.tar.gz ./dist

    artifacts:
        paths:
            - dist-uat.tar.gz
        expire_in: 1 week
